clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  test:
    environment:
      - NODE_ENV=development
    image: node:8
    pull: true
    commands:
      - echo $NODE_ENV
      - npm install
      - npm ls
      - npm run test
      - npm build
