pipeline:
  test:
    environment:
      - NODE_ENV=development
    image: node:10
    pull: true
    commands:
      - yarn install
      - npm run test
      - node packages/ai/dist/ai-cli.js

  publish:
    image: node:10
    when:
      branch: latest
    secrets:
      - npm_token
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npx lerna publish --repo-version $(node -p 'require("./lerna.json").version')-${DRONE_COMMIT:0:8} --skip-git --yes --npm-tag $DRONE_BRANCH --exact
