
pipeline:
  test:
    environment:
      - NODE_ENV=development
    image: node:10
    pull: true
    commands:
      - npm install
      - npm run test
      - npm --no-git-tag-version version "0.0.1-${DRONE_COMMIT:0:8}"
      - npm run build

  publish:
    image: node:10
    when:
      branch: latest
    secrets:
      - npm_token
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npm publish --tag $DRONE_BRANCH