
pipeline:
  test:
    environment:
      - NODE_ENV=development
    image: node:10
    pull: true
    commands:
      - yarn install
      - npm run test

  publish:
    image: node:10
    when:
      branch: latest
    secrets:
      - npm_token
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npm publish --tag $DRONE_BRANCH