
pipeline:
  test:
    environment:
      - NODE_ENV=development
    image: node:10
    pull: true
    commands:
      - npm install
      - npx lerna bootstrap
      - npm run test
      - npx lerna exec npm run prepare

  publish:
    image: node:10
    when:
      branch: latest
    secrets:
      - npm_token
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npx lerna publish --repo-version $(node -p 'require("./lerna.json").version')-$DRONE_BRANCH --skip-git --yes
